//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPIGET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVCONTEO
    {
        public int IDINV { get; set; }
        public string DESCRIPCION { get; set; }
        public int CANTIDAD { get; set; }
    }
}
